$SET VERIFY
$CC ST,FILEIN,INITIAL,INTERP,LEX,NAMES,NEWS,PARSER,PRIMITIVE,UNIXIO,MEMORY,-
 TTY
$LINK ST+MEMORY+NAMES+NEWS+INTERP+PRIMITIVE+FILEIN+LEX+PARSER+UNIXIO+TTY
$LINK INITIAL+MEMORY+NAMES+NEWS+INTERP+PRIMITIVE+FILEIN+LEX+PARSER+UNIXIO+TTY
$RUN INITIAL
$SET NOVERIFY
