"
 coded by Ketmar // Vampire Avalon (psyc://ketmar.no-ip.org/~Ketmar)
 Understanding is not required. Only obedience.

 This program is free software. It comes without any warranty, to
 the extent permitted by applicable law. You can redistribute it
 and/or modify it under the terms of the Do What The Fuck You Want
 To Public License, Version 2, as published by Sam Hocevar. See
 http://sam.zoy.org/wtfpl/COPYING for more details.
"
Package [
  FFI
]


FfiFunction extend [
  retType: aType with: anArg1 [
    <#FFICall func aType anArg1>.
    self primitiveFailed.
  ]
  retType: aType with: anArg1 with: anArg2 [
    <#FFICall func aType anArg1 anArg2>.
    self primitiveFailed.
  ]
  retType: aType with: anArg1 with: anArg2 with: anArg3 [
    <#FFICall func aType anArg1 anArg2 anArg3>.
    self primitiveFailed.
  ]
  retType: aType with: anArg1 with: anArg2 with: anArg3 with: anArg4 [
    <#FFICall func aType anArg1 anArg2 anArg3 anArg4>.
    self primitiveFailed.
  ]
  retType: aType with: anArg1 with: anArg2 with: anArg3 with: anArg4 with: anArg5 [
    <#FFICall func aType anArg1 anArg2 anArg3 anArg4 anArg5>.
    self primitiveFailed.
  ]
  retType: aType with: anArg1 with: anArg2 with: anArg3 with: anArg4 with: anArg5 with: anArg6 [
    <#FFICall func aType anArg1 anArg2 anArg3 anArg4 anArg5 anArg6>.
    self primitiveFailed.
  ]
  retType: aType with: anArg1 with: anArg2 with: anArg3 with: anArg4 with: anArg5 with: anArg6 with: anArg7 [
    <#FFICall func aType anArg1 anArg2 anArg3 anArg4 anArg5 anArg6 anArg7>.
    self primitiveFailed.
  ]
  retType: aType with: anArg1 with: anArg2 with: anArg3 with: anArg4 with: anArg5 with: anArg6 with: anArg7 with: anArg8 [
    <#FFICall func aType anArg1 anArg2 anArg3 anArg4 anArg5 anArg6 anArg7 anArg8>.
    self primitiveFailed.
  ]
  retType: aType with: anArg1 with: anArg2 with: anArg3 with: anArg4 with: anArg5 with: anArg6 with: anArg7 with: anArg8 with: anArg9 [
    <#FFICall func aType anArg1 anArg2 anArg3 anArg4 anArg5 anArg6 anArg7 anArg8 anArg9>.
    self primitiveFailed.
  ]
  retType: aType with: anArg1 with: anArg2 with: anArg3 with: anArg4 with: anArg5 with: anArg6 with: anArg7 with: anArg8 with: anArg9 with: anArg10 [
    <#FFICall func aType anArg1 anArg2 anArg3 anArg4 anArg5 anArg6 anArg7 anArg8 anArg9 anArg10>.
    self primitiveFailed.
  ]
  retType: aType with: anArg1 with: anArg2 with: anArg3 with: anArg4 with: anArg5 with: anArg6 with: anArg7 with: anArg8 with: anArg9 with: anArg10 with: anArg11 [
    <#FFICall func aType anArg1 anArg2 anArg3 anArg4 anArg5 anArg6 anArg7 anArg8 anArg9 anArg10 anArg11>.
    self primitiveFailed.
  ]
  retType: aType with: anArg1 with: anArg2 with: anArg3 with: anArg4 with: anArg5 with: anArg6 with: anArg7 with: anArg8 with: anArg9 with: anArg10 with: anArg11 with: anArg12 [
    <#FFICall func aType anArg1 anArg2 anArg3 anArg4 anArg5 anArg6 anArg7 anArg8 anArg9 anArg10 anArg11 anArg12>.
    self primitiveFailed.
  ]
  retType: aType with: anArg1 with: anArg2 with: anArg3 with: anArg4 with: anArg5 with: anArg6 with: anArg7 with: anArg8 with: anArg9 with: anArg10 with: anArg11 with: anArg12 with: anArg13 [
    <#FFICall func aType anArg1 anArg2 anArg3 anArg4 anArg5 anArg6 anArg7 anArg8 anArg9 anArg10 anArg11 anArg12 anArg13>.
    self primitiveFailed.
  ]
  retType: aType with: anArg1 with: anArg2 with: anArg3 with: anArg4 with: anArg5 with: anArg6 with: anArg7 with: anArg8 with: anArg9 with: anArg10 with: anArg11 with: anArg12 with: anArg13 with: anArg14 [
    <#FFICall func aType anArg1 anArg2 anArg3 anArg4 anArg5 anArg6 anArg7 anArg8 anArg9 anArg10 anArg11 anArg12 anArg13 anArg14>.
    self primitiveFailed.
  ]
  retType: aType with: anArg1 with: anArg2 with: anArg3 with: anArg4 with: anArg5 with: anArg6 with: anArg7 with: anArg8 with: anArg9 with: anArg10 with: anArg11 with: anArg12 with: anArg13 with: anArg14 with: anArg15 [
    <#FFICall func aType anArg1 anArg2 anArg3 anArg4 anArg5 anArg6 anArg7 anArg8 anArg9 anArg10 anArg11 anArg12 anArg13 anArg14 anArg15>.
    self primitiveFailed.
  ]
  retType: aType with: anArg1 with: anArg2 with: anArg3 with: anArg4 with: anArg5 with: anArg6 with: anArg7 with: anArg8 with: anArg9 with: anArg10 with: anArg11 with: anArg12 with: anArg13 with: anArg14 with: anArg15 with: anArg16 [
    <#FFICall func aType anArg1 anArg2 anArg3 anArg4 anArg5 anArg6 anArg7 anArg8 anArg9 anArg10 anArg11 anArg12 anArg13 anArg14 anArg15 anArg16>.
    self primitiveFailed.
  ]
  retType: aType with: anArg1 with: anArg2 with: anArg3 with: anArg4 with: anArg5 with: anArg6 with: anArg7 with: anArg8 with: anArg9 with: anArg10 with: anArg11 with: anArg12 with: anArg13 with: anArg14 with: anArg15 with: anArg16 with: anArg17 [
    <#FFICall func aType anArg1 anArg2 anArg3 anArg4 anArg5 anArg6 anArg7 anArg8 anArg9 anArg10 anArg11 anArg12 anArg13 anArg14 anArg15 anArg16 anArg17>.
    self primitiveFailed.
  ]
  retType: aType with: anArg1 with: anArg2 with: anArg3 with: anArg4 with: anArg5 with: anArg6 with: anArg7 with: anArg8 with: anArg9 with: anArg10 with: anArg11 with: anArg12 with: anArg13 with: anArg14 with: anArg15 with: anArg16 with: anArg17 with: anArg18 [
    <#FFICall func aType anArg1 anArg2 anArg3 anArg4 anArg5 anArg6 anArg7 anArg8 anArg9 anArg10 anArg11 anArg12 anArg13 anArg14 anArg15 anArg16 anArg17 anArg18>.
    self primitiveFailed.
  ]
  retType: aType with: anArg1 with: anArg2 with: anArg3 with: anArg4 with: anArg5 with: anArg6 with: anArg7 with: anArg8 with: anArg9 with: anArg10 with: anArg11 with: anArg12 with: anArg13 with: anArg14 with: anArg15 with: anArg16 with: anArg17 with: anArg18 with: anArg19 [
    <#FFICall func aType anArg1 anArg2 anArg3 anArg4 anArg5 anArg6 anArg7 anArg8 anArg9 anArg10 anArg11 anArg12 anArg13 anArg14 anArg15 anArg16 anArg17 anArg18 anArg19>.
    self primitiveFailed.
  ]
  retType: aType with: anArg1 with: anArg2 with: anArg3 with: anArg4 with: anArg5 with: anArg6 with: anArg7 with: anArg8 with: anArg9 with: anArg10 with: anArg11 with: anArg12 with: anArg13 with: anArg14 with: anArg15 with: anArg16 with: anArg17 with: anArg18 with: anArg19 with: anArg20 [
    <#FFICall func aType anArg1 anArg2 anArg3 anArg4 anArg5 anArg6 anArg7 anArg8 anArg9 anArg10 anArg11 anArg12 anArg13 anArg14 anArg15 anArg16 anArg17 anArg18 anArg19 anArg20>.
    self primitiveFailed.
  ]
  retType: aType with: anArg1 with: anArg2 with: anArg3 with: anArg4 with: anArg5 with: anArg6 with: anArg7 with: anArg8 with: anArg9 with: anArg10 with: anArg11 with: anArg12 with: anArg13 with: anArg14 with: anArg15 with: anArg16 with: anArg17 with: anArg18 with: anArg19 with: anArg20 with: anArg21 [
    <#FFICall func aType anArg1 anArg2 anArg3 anArg4 anArg5 anArg6 anArg7 anArg8 anArg9 anArg10 anArg11 anArg12 anArg13 anArg14 anArg15 anArg16 anArg17 anArg18 anArg19 anArg20 anArg21>.
    self primitiveFailed.
  ]
  retType: aType with: anArg1 with: anArg2 with: anArg3 with: anArg4 with: anArg5 with: anArg6 with: anArg7 with: anArg8 with: anArg9 with: anArg10 with: anArg11 with: anArg12 with: anArg13 with: anArg14 with: anArg15 with: anArg16 with: anArg17 with: anArg18 with: anArg19 with: anArg20 with: anArg21 with: anArg22 [
    <#FFICall func aType anArg1 anArg2 anArg3 anArg4 anArg5 anArg6 anArg7 anArg8 anArg9 anArg10 anArg11 anArg12 anArg13 anArg14 anArg15 anArg16 anArg17 anArg18 anArg19 anArg20 anArg21 anArg22>.
    self primitiveFailed.
  ]
  retType: aType with: anArg1 with: anArg2 with: anArg3 with: anArg4 with: anArg5 with: anArg6 with: anArg7 with: anArg8 with: anArg9 with: anArg10 with: anArg11 with: anArg12 with: anArg13 with: anArg14 with: anArg15 with: anArg16 with: anArg17 with: anArg18 with: anArg19 with: anArg20 with: anArg21 with: anArg22 with: anArg23 [
    <#FFICall func aType anArg1 anArg2 anArg3 anArg4 anArg5 anArg6 anArg7 anArg8 anArg9 anArg10 anArg11 anArg12 anArg13 anArg14 anArg15 anArg16 anArg17 anArg18 anArg19 anArg20 anArg21 anArg22 anArg23>.
    self primitiveFailed.
  ]
  retType: aType with: anArg1 with: anArg2 with: anArg3 with: anArg4 with: anArg5 with: anArg6 with: anArg7 with: anArg8 with: anArg9 with: anArg10 with: anArg11 with: anArg12 with: anArg13 with: anArg14 with: anArg15 with: anArg16 with: anArg17 with: anArg18 with: anArg19 with: anArg20 with: anArg21 with: anArg22 with: anArg23 with: anArg24 [
    <#FFICall func aType anArg1 anArg2 anArg3 anArg4 anArg5 anArg6 anArg7 anArg8 anArg9 anArg10 anArg11 anArg12 anArg13 anArg14 anArg15 anArg16 anArg17 anArg18 anArg19 anArg20 anArg21 anArg22 anArg23 anArg24>.
    self primitiveFailed.
  ]
  retType: aType with: anArg1 with: anArg2 with: anArg3 with: anArg4 with: anArg5 with: anArg6 with: anArg7 with: anArg8 with: anArg9 with: anArg10 with: anArg11 with: anArg12 with: anArg13 with: anArg14 with: anArg15 with: anArg16 with: anArg17 with: anArg18 with: anArg19 with: anArg20 with: anArg21 with: anArg22 with: anArg23 with: anArg24 with: anArg25 [
    <#FFICall func aType anArg1 anArg2 anArg3 anArg4 anArg5 anArg6 anArg7 anArg8 anArg9 anArg10 anArg11 anArg12 anArg13 anArg14 anArg15 anArg16 anArg17 anArg18 anArg19 anArg20 anArg21 anArg22 anArg23 anArg24 anArg25>.
    self primitiveFailed.
  ]
  retType: aType with: anArg1 with: anArg2 with: anArg3 with: anArg4 with: anArg5 with: anArg6 with: anArg7 with: anArg8 with: anArg9 with: anArg10 with: anArg11 with: anArg12 with: anArg13 with: anArg14 with: anArg15 with: anArg16 with: anArg17 with: anArg18 with: anArg19 with: anArg20 with: anArg21 with: anArg22 with: anArg23 with: anArg24 with: anArg25 with: anArg26 [
    <#FFICall func aType anArg1 anArg2 anArg3 anArg4 anArg5 anArg6 anArg7 anArg8 anArg9 anArg10 anArg11 anArg12 anArg13 anArg14 anArg15 anArg16 anArg17 anArg18 anArg19 anArg20 anArg21 anArg22 anArg23 anArg24 anArg25 anArg26>.
    self primitiveFailed.
  ]
  retType: aType with: anArg1 with: anArg2 with: anArg3 with: anArg4 with: anArg5 with: anArg6 with: anArg7 with: anArg8 with: anArg9 with: anArg10 with: anArg11 with: anArg12 with: anArg13 with: anArg14 with: anArg15 with: anArg16 with: anArg17 with: anArg18 with: anArg19 with: anArg20 with: anArg21 with: anArg22 with: anArg23 with: anArg24 with: anArg25 with: anArg26 with: anArg27 [
    <#FFICall func aType anArg1 anArg2 anArg3 anArg4 anArg5 anArg6 anArg7 anArg8 anArg9 anArg10 anArg11 anArg12 anArg13 anArg14 anArg15 anArg16 anArg17 anArg18 anArg19 anArg20 anArg21 anArg22 anArg23 anArg24 anArg25 anArg26 anArg27>.
    self primitiveFailed.
  ]
  retType: aType with: anArg1 with: anArg2 with: anArg3 with: anArg4 with: anArg5 with: anArg6 with: anArg7 with: anArg8 with: anArg9 with: anArg10 with: anArg11 with: anArg12 with: anArg13 with: anArg14 with: anArg15 with: anArg16 with: anArg17 with: anArg18 with: anArg19 with: anArg20 with: anArg21 with: anArg22 with: anArg23 with: anArg24 with: anArg25 with: anArg26 with: anArg27 with: anArg28 [
    <#FFICall func aType anArg1 anArg2 anArg3 anArg4 anArg5 anArg6 anArg7 anArg8 anArg9 anArg10 anArg11 anArg12 anArg13 anArg14 anArg15 anArg16 anArg17 anArg18 anArg19 anArg20 anArg21 anArg22 anArg23 anArg24 anArg25 anArg26 anArg27 anArg28>.
    self primitiveFailed.
  ]
  retType: aType with: anArg1 with: anArg2 with: anArg3 with: anArg4 with: anArg5 with: anArg6 with: anArg7 with: anArg8 with: anArg9 with: anArg10 with: anArg11 with: anArg12 with: anArg13 with: anArg14 with: anArg15 with: anArg16 with: anArg17 with: anArg18 with: anArg19 with: anArg20 with: anArg21 with: anArg22 with: anArg23 with: anArg24 with: anArg25 with: anArg26 with: anArg27 with: anArg28 with: anArg29 [
    <#FFICall func aType anArg1 anArg2 anArg3 anArg4 anArg5 anArg6 anArg7 anArg8 anArg9 anArg10 anArg11 anArg12 anArg13 anArg14 anArg15 anArg16 anArg17 anArg18 anArg19 anArg20 anArg21 anArg22 anArg23 anArg24 anArg25 anArg26 anArg27 anArg28 anArg29>.
    self primitiveFailed.
  ]
  retType: aType with: anArg1 with: anArg2 with: anArg3 with: anArg4 with: anArg5 with: anArg6 with: anArg7 with: anArg8 with: anArg9 with: anArg10 with: anArg11 with: anArg12 with: anArg13 with: anArg14 with: anArg15 with: anArg16 with: anArg17 with: anArg18 with: anArg19 with: anArg20 with: anArg21 with: anArg22 with: anArg23 with: anArg24 with: anArg25 with: anArg26 with: anArg27 with: anArg28 with: anArg29 with: anArg30 [
    <#FFICall func aType anArg1 anArg2 anArg3 anArg4 anArg5 anArg6 anArg7 anArg8 anArg9 anArg10 anArg11 anArg12 anArg13 anArg14 anArg15 anArg16 anArg17 anArg18 anArg19 anArg20 anArg21 anArg22 anArg23 anArg24 anArg25 anArg26 anArg27 anArg28 anArg29 anArg30>.
    self primitiveFailed.
  ]
  retType: aType with: anArg1 with: anArg2 with: anArg3 with: anArg4 with: anArg5 with: anArg6 with: anArg7 with: anArg8 with: anArg9 with: anArg10 with: anArg11 with: anArg12 with: anArg13 with: anArg14 with: anArg15 with: anArg16 with: anArg17 with: anArg18 with: anArg19 with: anArg20 with: anArg21 with: anArg22 with: anArg23 with: anArg24 with: anArg25 with: anArg26 with: anArg27 with: anArg28 with: anArg29 with: anArg30 with: anArg31 [
    <#FFICall func aType anArg1 anArg2 anArg3 anArg4 anArg5 anArg6 anArg7 anArg8 anArg9 anArg10 anArg11 anArg12 anArg13 anArg14 anArg15 anArg16 anArg17 anArg18 anArg19 anArg20 anArg21 anArg22 anArg23 anArg24 anArg25 anArg26 anArg27 anArg28 anArg29 anArg30 anArg31>.
    self primitiveFailed.
  ]
  retType: aType with: anArg1 with: anArg2 with: anArg3 with: anArg4 with: anArg5 with: anArg6 with: anArg7 with: anArg8 with: anArg9 with: anArg10 with: anArg11 with: anArg12 with: anArg13 with: anArg14 with: anArg15 with: anArg16 with: anArg17 with: anArg18 with: anArg19 with: anArg20 with: anArg21 with: anArg22 with: anArg23 with: anArg24 with: anArg25 with: anArg26 with: anArg27 with: anArg28 with: anArg29 with: anArg30 with: anArg31 with: anArg32 [
    <#FFICall func aType anArg1 anArg2 anArg3 anArg4 anArg5 anArg6 anArg7 anArg8 anArg9 anArg10 anArg11 anArg12 anArg13 anArg14 anArg15 anArg16 anArg17 anArg18 anArg19 anArg20 anArg21 anArg22 anArg23 anArg24 anArg25 anArg26 anArg27 anArg28 anArg29 anArg30 anArg31 anArg32>.
    self primitiveFailed.
  ]
]
